name: WA Checker 2.0

on:
  push:

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      
    - name: 'Unzip and Install'
      run: wmic path Win32_VideoController get VideoModeDescription,CurrentVerticalResolution,CurrentHorizontalResolution /format:value
